#!/bin/sh
# Cut the REAL outer-face machinery out of layout.lua into a loadable chunk, so the harness tests
# the engine's code and not a paraphrase of it. Same pattern as topo_extract.sh.
# ⚠ RE-CUT AFTER ANY EDIT to layout.lua -- a stale extract has already faked one failure in this
# project's history.
# Cuts: FANG + elro.faces (the rotation-system face tracer), face_area, face_turning (both file-local
# `local function`s), and elro.pick_outer_face.
L=../lua/topo.lua
OUT=outer_extract.lua

cut_local () {   # $1 = function name -> prints its source
  S=$(grep -n "^local function $1(" $L | head -1 | cut -d: -f1)
  E=$(awk -v s="$S" 'NR>=s && /^end$/ {print NR; exit}' $L)
  sed -n "${S},${E}p" $L
  echo "cut $1 ${S}-${E}" >&2
}
cut_global () {  # $1 = elro.<name>
  S=$(grep -n "^function elro.$1(" $L | head -1 | cut -d: -f1)
  E=$(awk -v s="$S" 'NR>=s && /^end$/ {print NR; exit}' $L)
  sed -n "${S},${E}p" $L
  echo "cut elro.$1 ${S}-${E}" >&2
}

FA=$(grep -n "^local FANG = " $L | head -1 | cut -d: -f1)
FE=$(awk -v s=$FA 'NR>=s && /^end$/ {print NR; exit}' $L)

{
  echo "-- GENERATED by outer_extract.sh -- do not edit, re-cut instead."
  echo "local elro = _G.elro"
  sed -n "${FA},${FE}p" $L          # FANG + elro.faces
  cut_local  face_area
  cut_local  face_turning
  cut_global pick_outer_face
} > $OUT
echo "-> $OUT" >&2
