-- GENERATED by outer_extract.sh -- do not edit, re-cut instead.
local elro = _G.elro
local FANG = { east = 0, northeast = 45, north = 90, northwest = 135,
               west = 180, southwest = 225, south = 270, southeast = 315 }

function elro.faces(nodeset, adj)
  local nb = {}
  for u in pairs(nodeset) do
    -- safe to yield from: the provers that call this under pcall declare a
    -- no-yield window (see elro.bg_tick).
    elro.bg_tick("faces")
    local lst = {}
    for d, v in each_exit(adj[u]) do
      if nodeset[v] and FANG[d] then lst[#lst + 1] = { v = v, ang = FANG[d] } end
    end
    table.sort(lst, function(a, b)
      if a.ang ~= b.ang then return a.ang < b.ang end
      return a.v < b.v
    end)
    nb[u] = lst
  end
  local function idx(u, v)
    for i, e in ipairs(nb[u]) do if e.v == v then return i end end
  end
  local visited, faces = {}, {}
  for u in pairs(nodeset) do
    elro.bg_tick("faces-trace")
    for _, e0 in ipairs(nb[u]) do
      if not visited[u .. ":" .. e0.v] then
        local face = {}
        local ca, cb = u, e0.v
        while not visited[ca .. ":" .. cb] do
          visited[ca .. ":" .. cb] = true
          face[#face + 1] = ca
          local i = idx(cb, ca)               -- reverse half-edge at cb
          local deg = #nb[cb]
          if not i or deg == 0 then break end  -- asymmetric exit: bail this face
          local ni = (i - 2) % deg + 1         -- clockwise predecessor (1-based)
          ca, cb = cb, nb[cb][ni].v
        end
        faces[#faces + 1] = face
      end
    end
  end
  return faces
end
local function face_area(face, adj)
  local cx, cy, pts = 0, 0, { { 0, 0 } }
  for i = 1, #face - 1 do
    local a, b, del = face[i], face[i + 1], nil
    for d, v in each_exit(adj[a]) do if v == b then del = elro.delta[d] ; break end end
    if del then cx = cx + del[1] ; cy = cy + del[2] end
    pts[#pts + 1] = { cx, cy }
  end
  local A = 0
  for i = 1, #pts do
    local p, q = pts[i], pts[(i % #pts) + 1]
    A = A + (p[1] * q[2] - q[1] * p[2])
  end
  return math.abs(A) / 2
end
local function face_turning(face, adj)
  local n = #face
  if n < 3 then return nil end
  local ang = {}
  for i = 1, n do
    local a, b, de = face[i], face[(i % n) + 1], nil
    for d, v in each_exit(adj[a]) do
      local dd = elro.delta[d]
      if v == b and dd and (dd[1] ~= 0 or dd[2] ~= 0) then de = dd ; break end
    end
    if not de then return nil end
    ang[i] = math.deg(math.atan2(de[2], de[1]))
  end
  local T = 0
  for i = 1, n do
    local t = (ang[(i % n) + 1] - ang[i]) % 360
    if t > 180 then t = t - 360 end
    if math.abs(math.abs(t) - 180) < 1e-6 then return nil end   -- reversal: not orientable
    T = T + t
  end
  return T
end
function elro.pick_outer_face(faces, adj)
  local neg, nneg = nil, 0
  for i, f in ipairs(faces) do
    elro.bg_tick("outer-face")
    if #f >= 3 then
      local seen, sim = {}, true
      for _, r in ipairs(f) do if seen[r] then sim = false ; break end ; seen[r] = true end
      local T = sim and face_turning(f, adj) or nil
      if T and T < 0 then neg, nneg = i, nneg + 1 end
    end
  end
  if nneg == 1 then return faces[neg], neg end
  local best, bestA, bi
  for i, f in ipairs(faces) do
    if #f >= 3 then
      local a = face_area(f, adj)
      if not best or a > bestA then best, bestA, bi = f, a, i end
    end
  end
  return best, bi
end
