-- GENERATED by topo_extract.sh -- do not edit, re-cut instead.
local elro = _G.elro
local FANG = { east = 0, northeast = 45, north = 90, northwest = 135,
               west = 180, southwest = 225, south = 270, southeast = 315 }

function elro.faces(nodeset, adj)
  local nb = {}
  for u in pairs(nodeset) do
    -- safe to yield from: the provers that call this under pcall declare a
    -- no-yield window (see elro.bg_tick).
    elro.bg_tick("faces")
    local lst = {}
    for d, v in each_exit(adj[u]) do
      if nodeset[v] and FANG[d] then lst[#lst + 1] = { v = v, ang = FANG[d] } end
    end
    table.sort(lst, function(a, b)
      if a.ang ~= b.ang then return a.ang < b.ang end
      return a.v < b.v
    end)
    nb[u] = lst
  end
  local function idx(u, v)
    for i, e in ipairs(nb[u]) do if e.v == v then return i end end
  end
  local visited, faces = {}, {}
  for u in pairs(nodeset) do
    elro.bg_tick("faces-trace")
    for _, e0 in ipairs(nb[u]) do
      if not visited[u .. ":" .. e0.v] then
        local face = {}
        local ca, cb = u, e0.v
        while not visited[ca .. ":" .. cb] do
          visited[ca .. ":" .. cb] = true
          face[#face + 1] = ca
          local i = idx(cb, ca)               -- reverse half-edge at cb
          local deg = #nb[cb]
          if not i or deg == 0 then break end  -- asymmetric exit: bail this face
          local ni = (i - 2) % deg + 1         -- clockwise predecessor (1-based)
          ca, cb = cb, nb[cb][ni].v
        end
        faces[#faces + 1] = face
      end
    end
  end
  return faces
end
function elro.topo_cross(adj, parallel_pair)
    -- Memoised on the adj table identity; a one-slot cache thrashes between graphs.
    local tmemo = elro._topoMemo
    if not tmemo then tmemo = setmetatable({}, { __mode = "k" }) ; elro._topoMemo = tmemo end
    local topoCache = tmemo[adj]
    if topoCache then return topoCache end
    -- `quartet` = the four rooms of each accepted pair (the two edges that must cross); the
    -- skeleton order lays these first so the crossing is established in open space.
    topoCache = { pair = {}, n = 0, faces = 0, genus = 0, quartet = {},
                  site = {}, nsite = 0, siteList = {} }
    local T = topoCache
    -- Stored BEFORE the analysis runs so the two cheap early returns below are cached too;
    -- otherwise planar areas recompute the whole analysis on every call.
    tmemo[adj] = topoCache
    local dlt = elro.delta
    -- (1) a working copy of the symmetrised adjacency, compass edges only
    local padj, ids = {}, {}
    for u, nb in pairs(adj) do
      local t = {}
      for d, v in pairs(nb) do
        local de = dlt[d]
        if de and adj[v] and (de[1] ~= 0 or de[2] ~= 0) then t[d] = v end
      end
      padj[u] = t ; ids[#ids + 1] = u
    end
    table.sort(ids)
    -- Symmetrise here, not at the caller: walk_branches hands in a symmetric adj but
    -- compose_spqr's is the raw directed adjacency, and the two must agree about the same map.
    for _, u in ipairs(ids) do
      for d, v in each_exit(padj[u]) do
        if padj[v] then
          local back = false
          for _, w in each_exit(padj[v]) do if w == u then back = true ; break end end
          if not back then
            local rv = elro.reverse[d]
            if rv and padj[v][rv] == nil then padj[v][rv] = u end
          end
        end
      end
    end
    local function dirOf(u, v) for d, w in each_exit(padj[u]) do if w == v then return d end end end
    local function isD(d) local de = dlt[d] ; return de and de[1] ~= 0 and de[2] ~= 0 end
    -- (1) permitted grid-X: an axial 4-cycle a-b-c-d carrying both diagonals. Enumerated over
    -- common neighbours -- O(E * deg^2), not O(V^3).
    local dummies, nd = {}, 0
    do
      local seenq = {}
      for _, a in ipairs(ids) do
        for d1, c in each_exit(padj[a]) do
          if isD(d1) and padj[c] then
            local axial = {}
            for d2, b in each_exit(padj[a]) do
              if not isD(d2) then
                local dbc = dirOf(b, c)
                if dbc and not isD(dbc) then axial[#axial + 1] = b end
              end
            end
            for i = 1, #axial do
              for j = 1, #axial do
                if i ~= j then
                  local b, dd = axial[i], axial[j]
                  local dbd = dirOf(b, dd)
                  if dbd and isD(dbd) then
                    local q = { a, b, c, dd } ; table.sort(q)
                    local k = table.concat(q, ",")
                    if not seenq[k] then
                      seenq[k] = true
                      nd = nd + 1
                      local X = -nd                    -- dummy ids are negative: never a room id
                      padj[X] = {} ; dummies[X] = true ; ids[#ids + 1] = X
                      local function relink(u, w)      -- u -dir-> w  becomes  u -dir-> X -dir-> w
                        local dv = dirOf(u, w) ; if not dv then return end
                        local rv = elro.reverse[dv] ; if not rv then return end
                        padj[u][dv] = X ; padj[X][rv] = u
                        padj[X][dv] = w ; padj[w][rv] = X
                      end
                      relink(a, c) ; relink(b, dd)
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    -- (2) 2-core
    local core, alive = {}, {}
    for _, u in ipairs(ids) do alive[u] = true end
    local changed = true
    while changed do
      changed = false
      for _, u in ipairs(ids) do
        if alive[u] then
          local n = 0
          for _, v in each_exit(padj[u]) do if alive[v] then n = n + 1 end end
          if n <= 1 then alive[u] = false ; changed = true end
        end
      end
    end
    local nCore = 0
    for _, u in ipairs(ids) do if alive[u] then core[u] = true ; nCore = nCore + 1 end end
    if nCore < 4 then return T end
    local nbrs = {}
    for u in pairs(core) do
      local l = {}
      for _, v in each_exit(padj[u]) do if core[v] then l[#l + 1] = v end end
      table.sort(l) ; nbrs[u] = l
    end
    -- (3) genus per component: V - E + F = 2 - 2g. Genus 0 everywhere => a crossing-free drawing
    -- exists => nothing below can be forced, and this is the cheap exit taken by most areas.
    local faces = elro.faces(core, padj)
    local par = {}
    local function find(a) while par[a] and par[a] ~= a do par[a] = par[par[a]] ; a = par[a] end return a end
    for u in pairs(core) do par[u] = par[u] or u end
    local V, E = nCore, 0
    for u in pairs(core) do
      E = E + #nbrs[u]
      for _, v in ipairs(nbrs[u]) do
        local ra, rb = find(u), find(v) ; if ra ~= rb then par[ra] = rb end
      end
    end
    E = E / 2
    local comps = {}
    for u in pairs(core) do comps[find(u)] = true end
    local nC = 0 ; for _ in pairs(comps) do nC = nC + 1 end
    local g = (2 * nC - V + E - #faces) / 2
    T.genus = g
    -- (3b) Genus is a SPHERE test but the drawing lives in the PLANE: a face turning +360 bounds
    -- a bounded region and is fine anywhere; a face turning -360 demands to be the outer face,
    -- and two such faces in one component cannot both be satisfied. Per-face turn is hoisted
    -- here so this gate can read it; `angOf` keeps the same first-hit-in-pairs-order semantics
    -- as the old per-half-edge rescan but is O(E) once. (Named angOf, not dirOf -- dirOf is
    -- already a function in this scope.)
    local angOf = {}
    for a in pairs(core) do
      local m = {}
      for d, w in each_exit(padj[a]) do
        local dd = dlt[d]
        if dd and (dd[1] ~= 0 or dd[2] ~= 0) and m[w] == nil then
          m[w] = math.deg(math.atan2(dd[2], dd[1]))
        end
      end
      angOf[a] = m
    end
    local fturn, outerClaims, claimByComp = {}, 0, {}
    for fi, f in ipairs(faces) do
      local n = #f
      if n >= 3 then
        local turn, ok = 0, true
        local prev = (angOf[f[n]] or {})[f[1]]
        if not prev then ok = false end
        for i = 1, n do
          if not ok then break end
          local cur = (angOf[f[i]] or {})[f[(i % n) + 1]]
          if not cur then ok = false break end
          local t = (cur - prev) % 360 ; if t > 180 then t = t - 360 end
          turn = turn + t ; prev = cur
        end
        if ok then
          fturn[fi] = turn
          -- Count outer-face claims per 2-core component and take the worst: two claimants only conflict in the same component.
          if turn <= -359 then
            local c = find(f[1])
            claimByComp[c] = (claimByComp[c] or 0) + 1
            if claimByComp[c] > outerClaims then outerClaims = claimByComp[c] end
          end
        end
      end
    end
    T.outerClaims = outerClaims
    if g <= 0 and outerClaims <= 1 then return T end
    local unresolved = {}   -- non-closing faces that produced no interleaving pair
    -- (4) per-face turn: only a face that cannot close as a simple curve can force anything
    local cap = TUNE.topoFaceCap
    local budget = TUNE.topoBudget
    -- Wall-clock bail as well as the step budget: longest-cycle enumeration is exponential in the worst case, and a timeout degrades to no sites from this face.
    local tStart, tCap = os.clock(), (elro.topoTimeCap or 0.5)
    elro.tr("topo crossings: analysing (" .. #faces .. " faces)")
    for fi, f in ipairs(faces) do
      local n = #f
      do
        local turn = fturn[fi]
        if turn then
          if math.abs(math.abs(turn) - 360) > 1 then
            -- distinct rooms of this face
            local S, ns = {}, 0
            for i = 1, n do if not S[f[i]] then S[f[i]] = true ; ns = ns + 1 end end
            if ns >= 4 and ns <= cap and budget > 0 then
              T.faces = T.faces + 1
              local pairsBefore = T.n
              -- (5) The rings of this face, then the bridges hanging off each.
              -- Keep every maximal ring, not one winner: the longest cycle ties routinely and
              -- the tie decides the answer. The union over maximal rings is also the right
              -- answer: each ring names a legitimate site for the same forced crossing.
              local rings, bestLen, ringSeen = {}, 0, {}
              local maxRings = TUNE.topoRings
              do
                local function canon(c)             -- rotation- and direction-independent key
                  local m, mi = c[1], 1
                  for i = 2, #c do if c[i] < m then m, mi = c[i], i end end
                  local fwd, bwd = {}, {}
                  for i = 0, #c - 1 do
                    fwd[#fwd + 1] = c[(mi - 1 + i) % #c + 1]
                    bwd[#bwd + 1] = c[(mi - 1 - i) % #c + 1]
                  end
                  local a, b = table.concat(fwd, ","), table.concat(bwd, ",")
                  return (a < b) and a or b
                end
                local function keep(path)
                  if #path < bestLen then return end
                  if #path > bestLen then rings, bestLen, ringSeen = {}, #path, {} end
                  if #rings >= maxRings then return end
                  local c = {} ; for i = 1, #path do c[i] = path[i] end
                  local k = canon(c)
                  if not ringSeen[k] then ringSeen[k] = true ; rings[#rings + 1] = c end
                end
                local order = {} ; for u in pairs(S) do order[#order + 1] = u end
                table.sort(order)
                for _, s0 in ipairs(order) do
                  local path, on = { s0 }, { [s0] = true }
                  local function dfs(u)
                    if budget <= 0 then return end
                    for _, v in ipairs(nbrs[u]) do
                      if S[v] then
                        budget = budget - 1
                        if budget % 4096 == 0 and (os.clock() - tStart) > tCap then budget = 0 end
                        if budget <= 0 then return end
                        if v == s0 then
                          if #path >= 4 then keep(path) end
                        elseif v > s0 and not on[v] then
                          path[#path + 1] = v ; on[v] = true
                          dfs(v)
                          on[v] = nil ; path[#path] = nil
                        end
                      end
                    end
                  end
                  dfs(s0)
                  if budget <= 0 then break end
                end
              end
              for _, ring in ipairs(rings) do
                T.rings = (T.rings or 0) + 1
                local onR, idxR = {}, {}
                for i, u in ipairs(ring) do onR[u] = true ; idxR[u] = i end
                local cycE = {}
                for i = 1, #ring do
                  local a, b = ring[i], ring[(i % #ring) + 1]
                  cycE[a .. ":" .. b] = true ; cycE[b .. ":" .. a] = true
                end
                local brs, doneC = {}, {}
                for i = 1, #ring do
                  for _, v in ipairs(nbrs[ring[i]]) do
                    if onR[v] and not cycE[ring[i] .. ":" .. v] then
                      local k = ekey(ring[i], v)
                      if not doneC[k] then
                        doneC[k] = true
                        brs[#brs + 1] = { att = { idxR[ring[i]], idxR[v] }, inner = {},
                                          edges = { { ring[i], v } } }
                      end
                    end
                  end
                end
                local mark = {}
                for u in pairs(core) do
                  if not onR[u] and not mark[u] then
                    local comp, st, att = {}, { u }, {}
                    mark[u] = true
                    while #st > 0 do
                      local x = table.remove(st) ; comp[#comp + 1] = x
                      for _, v in ipairs(nbrs[x]) do
                        if onR[v] then att[idxR[v]] = true
                        elseif not mark[v] then mark[v] = true ; st[#st + 1] = v end
                      end
                    end
                    local a = {} ; for i in pairs(att) do a[#a + 1] = i end
                    table.sort(a)
                    -- a bridge at least as big as its ring is the REST OF THE MAP, not a site
                    if #a >= 2 and #comp < #ring then
                      local es, inSet = {}, {}
                      for _, x in ipairs(comp) do inSet[x] = true end
                      local seenE = {}
                      for _, x in ipairs(comp) do
                        for _, v in ipairs(nbrs[x]) do
                          if inSet[v] or onR[v] then
                            local k = ekey(x, v)
                            if not seenE[k] then seenE[k] = true ; es[#es + 1] = { x, v } end
                          end
                        end
                      end
                      brs[#brs + 1] = { att = a, inner = comp, edges = es }
                    end
                  end
                end
                local function interleaves(b1, b2)
                  for _, i in ipairs(b1.att) do
                    for _, j in ipairs(b1.att) do
                      if i < j then
                        local ins, outs = false, false
                        for _, k in ipairs(b2.att) do
                          if k ~= i and k ~= j then
                            if k > i and k < j then ins = true else outs = true end
                          end
                        end
                        if ins and outs then return true end
                      end
                    end
                  end
                  return false
                end
                for i = 1, #brs do
                  for j = i + 1, #brs do
                    if interleaves(brs[i], brs[j]) or interleaves(brs[j], brs[i]) then
                      for _, e1 in ipairs(brs[i].edges) do
                        for _, e2 in ipairs(brs[j].edges) do
                          -- an edge through a dummy is half of a permitted grid-X: already exempt
                          if not (dummies[e1[1]] or dummies[e1[2]]
                               or dummies[e2[1]] or dummies[e2[2]])
                             -- provably parallel pairs (both edges locked to one row class, or
                             -- one column class) can never meet
                             and not (parallel_pair and parallel_pair(e1[1], e1[2], e2[1], e2[2])) then
                            local k1, k2 = ekey(e1[1], e1[2]), ekey(e2[1], e2[2])
                            if k1 ~= k2 then
                              local k = crosspair(k1, k2)
                              if not T.pair[k] then
                                T.pair[k] = true ; T.n = T.n + 1
                                T.quartet[#T.quartet + 1] = { e1[1], e1[2], e2[1], e2[2] }
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
              -- A face that cannot close and produced no interleaving pair is unresolved -- the
              -- figure-eight case: the maximal cycle runs through both lobes, so the chain the
              -- crossing belongs in becomes ring edges, which are never reported as crossing.
              if T.n == pairsBefore then unresolved[#unresolved + 1] = S end
            end
          end
        end
      end
    end
    -- Clean-chain sites: the answer for unresolved faces. A crossing may sit in any gap of a
    -- maximal degree-2 run; a room that hangs anything outside the 2-core is a WALL. Unlike a
    -- bridge pair this names ONE edge, not two -- the partner is whatever the loop ends up
    -- routing through the gap.
    if #unresolved > 0 and elro.chainSites ~= false then
      local used = {}
      for u in pairs(core) do
        if #nbrs[u] == 2 and not used[u] then
          local ch = { u } ; used[u] = true
          for side = 1, 2 do
            local prev, cur = u, nbrs[u][side]
            while cur and core[cur] and #nbrs[cur] == 2 and not used[cur] do
              used[cur] = true
              if side == 1 then ch[#ch + 1] = cur else table.insert(ch, 1, cur) end
              local nxt
              for _, w in ipairs(nbrs[cur]) do if w ~= prev then nxt = w end end
              prev, cur = cur, nxt
            end
          end
          -- The chain's TERMINAL JUNCTIONS belong to the run for gap purposes: the gap next to one
          -- is legal, so the run is [j1] + ch + [j2].
          local run = {}
          do
            local function term(endRoom, inward)
              for _, w in ipairs(nbrs[endRoom]) do if w ~= inward then return w end end
            end
            local j1 = term(ch[1], ch[2])
            local j2 = term(ch[#ch], ch[#ch - 1])
            if j1 and j1 ~= ch[1] then run[#run + 1] = j1 end
            for _, r in ipairs(ch) do run[#run + 1] = r end
            if j2 and j2 ~= ch[#ch] and j2 ~= j1 then run[#run + 1] = j2 end
          end
          -- A WALL is a chain room hanging a subtree outside the 2-core; a terminal junction is
          -- not a wall (what hangs off it is the loop itself). A gap is legal unless BOTH its
          -- rooms hang structure -- a wire threaded between two pendant-carrying rooms has
          -- nowhere to go. Walls split the chain into ZONES; the crossing runs between zones.
          local inCh = {}
          for _, r in ipairs(ch) do inCh[r] = true end
          local function wall(r)
            if not inCh[r] then return false end
            local n2 = 0 ; for _ in each_exit(padj[r]) do n2 = n2 + 1 end
            return n2 > 2
          end
          local function freeBead(r)
            local n2 = 0 ; for _ in each_exit(padj[r]) do n2 = n2 + 1 end
            return n2 == 2
          end
          -- T.site feeds two uses, deliberately split: every in-face gap of the chain is
          -- LICENSED at topo_forced (the chain provably must be crossed somewhere; which gap the
          -- geometry lands on is the walk's business), but only unwalled gaps may SEED via
          -- `zones` below. The licence is per-edge and has no budget, unlike the wire prover's.
          local zones, cur = {}, nil
          for i = 1, #run - 1 do
            local a, b = run[i], run[i + 1]
            if not dummies[a] and not dummies[b] then
              local inFace = false
              for _, S in ipairs(unresolved) do if S[a] and S[b] then inFace = true ; break end end
              local walled = wall(a) and wall(b)
              if inFace then
                local k = ekey(a, b)
                if not T.site[k] then
                  T.site[k] = true ; T.nsite = T.nsite + 1
                  T.siteList[#T.siteList + 1] = { a, b, walled = walled or nil }
                end
              end
              if inFace and not walled then
                local score = (freeBead(a) and 1 or 0) + (freeBead(b) and 1 or 0)
                if not cur then cur = { gaps = {} } ; zones[#zones + 1] = cur end
                cur.gaps[#cur.gaps + 1] = { a, b, score }
              else cur = nil end                     -- a walled gap ENDS the zone
            else cur = nil end
          end
          -- Seed pair: two gaps of the same chain (a figure-eight is the chain folding back
          -- across itself), taken from two zones either side of the walled middle. Tie-break =
          -- smallest rectangle: the last gap of one zone against the first of the next -- the
          -- two gaps facing each other across the walls; a tighter fold is less stretch.
          for i = 1, #zones - 1 do
            local z1, z2 = zones[i], zones[i + 1]
            local g1, g2 = z1.gaps[#z1.gaps], z2.gaps[1]
            T.quartet[#T.quartet + 1] = { g1[1], g1[2], g2[1], g2[2], chain = true }
            T.chainQuartet = (T.chainQuartet or 0) + 1
            break                                    -- one seed per chain
          end
        end
      end
    end
    -- Publish what the build found, separately from what the walk went on to use.
    elro._tcGenus, elro._tcPairs, elro._tcFaces, elro._tcRan = T.genus, T.n, T.faces, true
    elro._tcSites = T.nsite
    if elro.debug or T.n > 0 or T.nsite > 0 then
      elro.tr(string.format("topo crossings: genus %.0f, %d outer-claiming face(s), %d non-closing"
        .. " face(s), %d ring(s), %d accepted pair(s), %d chain site(s)",
        T.genus, T.outerClaims or 0, T.faces, T.rings or 0, T.n, T.nsite))
      for _, s in ipairs(T.siteList) do
        -- A walled site is licence-only: it may be crossed but never seeds a constructed pair.
        elro.tr(string.format("  chain site: %s-%s (a legal gap in a clean chain of a face that cannot close)%s",
          tostring(s[1]), tostring(s[2]),
          s.walled and " [WALLED -- licence only, never seeds]" or ""))
      end
    end
    return T
end
