#!/bin/sh
# Cut the REAL elro.topo_cross (and elro.faces, which it calls) out of layout.lua into a loadable
# chunk, so the harness tests the engine's code and not a paraphrase of it.
# ⚠ RE-CUT AFTER ANY EDIT to layout.lua -- a stale extract has already faked one failure in this
# project's history.
# NB topo_cross moved to MODULE scope so compose_spqr's seed choice can call it too; the cut got
# simpler as a result (no wrapper closure, no ekey2 injection -- it carries its own).
L=../lua/topo.lua
OUT=topo_extract.lua

FA=$(grep -n "^local FANG = " $L | head -1 | cut -d: -f1)
FE=$(awk -v s=$FA 'NR>=s && /^end$/ {print NR; exit}' $L)
TS=$(grep -n "^function elro.topo_cross" $L | cut -d: -f1)
TE=$(awk -v s=$TS 'NR>=s && /^end$/ {print NR; exit}' $L)

{
  echo "-- GENERATED by topo_extract.sh -- do not edit, re-cut instead."
  echo "local elro = _G.elro"
  sed -n "${FA},${FE}p" $L
  sed -n "${TS},${TE}p" $L
} > $OUT
echo "cut FANG/faces ${FA}-${FE}, topo_cross ${TS}-${TE} -> $OUT"
