#!/bin/sh
# Cut the REAL elro.wire_cross out of layout.lua into a loadable chunk, so the harness tests the
# engine's code and not a paraphrase of it. Same mechanism as topo_extract.sh.
# ⚠ RE-CUT AFTER ANY EDIT to layout.lua -- a stale extract has already faked one failure in this
# project's history (and the stale copy happened to be a faithful model of the very bug it was
# supposed to catch, which is why it was believed).
# wire_cross is MODULE scope and fully self-contained (it reads only `adj` and elro.delta), so the
# cut is a single span with no wrapper closure and no injected locals.
L=../lua/topo.lua
OUT=wire_extract.lua

# wire_lt is the shared reachability primitive; wire_cross takes it as `local lt = elro.wire_lt`, so
# the cut MUST include it or the extract loads and then fails at call time.
LS=$(grep -n "^function elro.wire_lt" $L | cut -d: -f1)
LE=$(awk -v s=$LS 'NR>=s && /^end$/ {print NR; exit}' $L)
WS=$(grep -n "^function elro.wire_cross" $L | cut -d: -f1)
WE=$(awk -v s=$WS 'NR>=s && /^end$/ {print NR; exit}' $L)
# wire_site_min is the BUDGET. It is at module scope taking `coord` as an argument precisely so the
# harness can drive it -- a walk-local closure over `coord` would be untestable, which is how
# pull_makes_lie shipped with two bugs.
BS=$(grep -n "^function elro.wire_site_min" $L | cut -d: -f1)
BE=$(awk -v s=$BS 'NR>=s && /^end$/ {print NR; exit}' $L)

{
  echo "-- GENERATED by wire_extract.sh -- do not edit, re-cut instead."
  echo "local elro = _G.elro"
  sed -n "${LS},${LE}p" $L
  sed -n "${WS},${WE}p" $L
  sed -n "${BS},${BE}p" $L
} > $OUT
echo "cut wire_lt ${LS}-${LE}, wire_cross ${WS}-${WE}, wire_site_min ${BS}-${BE} -> $OUT"
