-- GENERATED by wire_extract.sh -- do not edit, re-cut instead.
local elro = _G.elro
function elro.wire_lt(A, ca, cb)
  if ca == cb then return false end
  local s = A.reach[ca]
  if not s then
    s = {}
    local stack = {}
    for x in pairs(A.succ[ca] or {}) do stack[#stack + 1] = x end
    while #stack > 0 do
      local x = table.remove(stack)
      if not s[x] then s[x] = true
        for y in pairs(A.succ[x] or {}) do if not s[y] then stack[#stack + 1] = y end end
      end
    end
    A.reach[ca] = s
  end
  return s[cb] == true
end
function elro.wire_cross(adj)
  -- Memoised on the adj table identity, not one slot: distinct adjacency tables alternate here
  -- and a single-slot cache thrashes.
  local memo = elro._wireMemo
  if not memo then memo = setmetatable({}, { __mode = "k" }) ; elro._wireMemo = memo end
  local hit = memo[adj] ; if hit then return hit end
  local W = { O = {}, pair = {}, pairIdx = {}, n = 0, min = 0, quartet = {}, wires = {},
              cycles = 0, cycleAxis = nil, sameClassArcs = 0, badArcs = {} }
  memo[adj] = W
  local dlt = elro.delta

  -- (1) Per axis: equality classes (union-find over edges that do not move on this axis) and
  -- strict-order arcs between classes, kept in both directions -- the backward table answers
  -- "strictly inside that wire's span" with one BFS per side.
  for axis = 1, 2 do
    local p = {}
    local function find(a)
      if p[a] == nil then p[a] = a end
      while p[a] ~= a do p[a] = p[p[a]] ; a = p[a] end
      return a
    end
    for r, nb in pairs(adj) do
      find(r)
      for d, v in pairs(nb) do
        local de = dlt[d]
        if de and adj[v] and (de[1] ~= 0 or de[2] ~= 0) and de[axis] == 0 then
          local ra, rb = find(r), find(v) ; if ra ~= rb then p[ra] = rb end
        end
      end
    end
    local succ, pred, seen = {}, {}, {}
    for r, nb in pairs(adj) do
      for d, v in pairs(nb) do
        local de = dlt[d]
        -- `v ~= r` skips self-loops here, not in tier 0(b) below: self-loops never enter the
        -- layout graph, so reporting one as infeasible would be a permanent false alarm.
        if de and adj[v] and v ~= r and (de[1] ~= 0 or de[2] ~= 0) and de[axis] ~= 0 then
          local a, b
          if de[axis] > 0 then a, b = find(r), find(v) else a, b = find(v), find(r) end
          if a ~= b then
            succ[a] = succ[a] or {} ; succ[a][b] = true
            pred[b] = pred[b] or {} ; pred[b][a] = true
          else
            -- Tier 0(b): a strict order demanded between rooms locked to one class means no
            -- truthful drawing exists (a forced lie, not a crossing). Counted per canonical
            -- pair, since a symmetric adj presents every edge twice. Reported only.
            local k = ekey(r, v)
            if not seen[k] then
              seen[k] = true
              W.sameClassArcs = W.sameClassArcs + 1
              if #W.badArcs < 8 then
                W.badArcs[#W.badArcs + 1] = string.format("%d-%s->%d (axis %d)", r, d, v, axis)
              end
            end
          end
        end
      end
    end
    -- field names match eqw_order's so the two can be folded together later without churn
    W.O[axis] = { find = find, succ = succ, pred = pred, reach = {} }
  end

  -- (2) Tier 0(a): a cycle in an axis order DAG means no truthful drawing exists. Kahn: any
  -- class left with non-zero in-degree is on or downstream of a cycle.
  for axis = 1, 2 do
    local A = W.O[axis]
    local indeg, nn = {}, 0
    for a, s in pairs(A.succ) do
      if indeg[a] == nil then indeg[a] = 0 ; nn = nn + 1 end
      for b in pairs(s) do
        if indeg[b] == nil then indeg[b] = 1 ; nn = nn + 1 else indeg[b] = indeg[b] + 1 end
      end
    end
    local q, done = {}, 0
    for a, d in pairs(indeg) do if d == 0 then q[#q + 1] = a end end
    while #q > 0 do
      local a = table.remove(q) ; done = done + 1
      for b in pairs(A.succ[a] or {}) do
        indeg[b] = indeg[b] - 1
        if indeg[b] == 0 then q[#q + 1] = b end
      end
    end
    if done < nn then
      W.cycles = W.cycles + (nn - done)
      W.cycleAxis = W.cycleAxis or axis
    end
  end

  -- (3) strict reachability. `lt` is the single-class form; `reach_set` the set form -- one BFS
  -- seeded from every class of a wire at once, O(E) per wire instead of per room.
  local lt = elro.wire_lt          -- ONE implementation, shared with the place_room order clamp
  local function reach_set(tbl, seeds)
    local s, stack = {}, {}
    for k in pairs(seeds) do for x in pairs(tbl[k] or {}) do stack[#stack + 1] = x end end
    while #stack > 0 do
      local x = table.remove(stack)
      if not s[x] then s[x] = true
        for y in pairs(tbl[x] or {}) do if not s[y] then stack[#stack + 1] = y end end
      end
    end
    return s
  end

  -- (4) The wires. A single-room class spans nothing and is not a wire. `inside[axis][c]` = the
  -- classes on the other axis provably strictly within class c's span.
  local mem = { {}, {} }
  for r in pairs(adj) do
    for axis = 1, 2 do
      local c = W.O[axis].find(r)
      local m = mem[axis][c] ; if m then m[#m + 1] = r else mem[axis][c] = { r } end
    end
  end
  local inside = { {}, {} }
  for axis = 1, 2 do
    local other = 3 - axis
    local A = W.O[other]
    for c, ms in pairs(mem[axis]) do
      if #ms >= 2 then
        local seeds = {}
        for i = 1, #ms do seeds[A.find(ms[i])] = true end
        local fwd, bwd = reach_set(A.succ, seeds), reach_set(A.pred, seeds)
        local ins, any = {}, false
        for k in pairs(fwd) do if bwd[k] then ins[k] = true ; any = true end end
        if any then inside[axis][c] = ins end
      end
    end
  end

  -- (5) The pairs. Iterating the small `inside` sets keeps this O(sum |inside|), not O(classes^2).
  for cv, insY in pairs(inside[1]) do            -- cv = a COLUMN class = a vertical wire
    local vm = mem[1][cv]
    local vset = {}                              -- hoisted: invariant across the ch loop
    for i = 1, #vm do vset[vm[i]] = true end
    for ch in pairs(insY) do                     -- ch = a row class strictly inside cv's row span
      local insX = inside[2][ch]
      if insX and insX[cv] then
        -- Disjoint room sets: a shared room satisfies the meeting legitimately (which is what
        -- stops plain grids and diagonal quads from proving anything).
        local hm = mem[2][ch]
        local share = false
        for i = 1, #hm do if vset[hm[i]] then share = true ; break end end
        if not share then
          -- The witness: one member of each wire on each side of the meeting point -- the
          -- quartet block_needs_cross tests for containment. Take the TIGHTEST bracket
          -- (DAG-maximal among those proved below, DAG-minimal among those proved above): it is
          -- the right walk root and likelier to lie wholly inside one block. Ties break by
          -- lowest room id, never by iteration order (hash-seed dependent).
          local O1, O2 = W.O[1], W.O[2]
          local function tightest(ms, A, target, below)
            local cand = {}
            for i = 1, #ms do
              local c = A.find(ms[i])
              if below and lt(A, c, target) or not below and lt(A, target, c) then
                cand[#cand + 1] = ms[i]
              end
            end
            local best
            for _, r in ipairs(cand) do
              local outer = false        -- is some other candidate strictly INSIDE r's side?
              for _, q in ipairs(cand) do
                if q ~= r then
                  local a, b = A.find(r), A.find(q)
                  if below and lt(A, a, b) or not below and lt(A, b, a) then outer = true ; break end
                end
              end
              if not outer and (best == nil or r < best) then best = r end
            end
            return best
          end
          local S  = tightest(vm, O2, ch, true)
          local N  = tightest(vm, O2, ch, false)
          local Wr = tightest(hm, O1, cv, true)
          local Er = tightest(hm, O1, cv, false)
          -- The site: the crossing must be between an internal edge of V spanning row `ch` and
          -- one of H spanning column `cv`; where a wire is non-monotone fall back to all its
          -- internal edges. `de[sameAxis] == 0` is not redundant with the class test: dropping
          -- it leaks a diagonal, and this prover must never be able to name a diagonal x
          -- diagonal grid-X (that is a free crossing).
          local function span_edges(ms, sameAxis, spanAxis, target)
            local es, n = {}, 0
            local Asame, Aspan = W.O[sameAxis], W.O[spanAxis]
            local function internal(u, v, de)
              return de and adj[v] and de[sameAxis] == 0 and de[spanAxis] ~= 0
                     and Asame.find(v) == Asame.find(u)
            end
            for i = 1, #ms do
              local u = ms[i]
              for d, v in each_exit(adj[u]) do
                if internal(u, v, dlt[d]) then
                  local a, b = Aspan.find(u), Aspan.find(v)
                  if lt(Aspan, a, target) and lt(Aspan, target, b)
                     or lt(Aspan, b, target) and lt(Aspan, target, a) then
                    local k = ekey(u, v) ; if not es[k] then es[k] = true ; n = n + 1 end
                  end
                end
              end
            end
            if n == 0 then
              -- Undetermined: no single edge provably brackets the target, so every internal
              -- edge is a candidate -- except an edge with both endpoints proved on the same
              -- side of the target, which cannot span it.
              for i = 1, #ms do
                local u = ms[i]
                for d, v in each_exit(adj[u]) do
                  if internal(u, v, dlt[d]) then
                    local a, b = Aspan.find(u), Aspan.find(v)
                    local bothLo = lt(Aspan, a, target) and lt(Aspan, b, target)
                    local bothHi = lt(Aspan, target, a) and lt(Aspan, target, b)
                    if not bothLo and not bothHi then
                      local k = ekey(u, v) ; if not es[k] then es[k] = true ; n = n + 1 end
                    end
                  end
                end
              end
            end
            return es, n
          end
          local ves, vn = span_edges(vm, 1, 2, ch)   -- V: one column class, spans ROWS
          local hes, hn = span_edges(hm, 2, 1, cv)   -- H: one row class,    spans COLUMNS
          if vn > 0 and hn > 0 then
            W.n = W.n + 1
            W.min = W.n
            W.wires[W.n] = { cv = cv, ch = ch, vm = vm, hm = hm, ves = ves, hes = hes,
                             S = S, N = N, W = Wr, E = Er, vn = vn, hn = hn }
            if S and N and Wr and Er then W.quartet[#W.quartet + 1] = { S, N, Wr, Er } end
            -- `pairIdx` maps each key back to its forced pair, not just a boolean: the site is
            -- a range so the cross product holds many keys while the proof licenses exactly ONE
            -- meeting -- the caller must reach the pair to budget it.
            for k1 in pairs(ves) do
              for k2 in pairs(hes) do
                local k = crosspair(k1, k2)
                W.pair[k] = true ; W.pairIdx[k] = W.n
              end
            end
          end
        end
      end
    end
  end
  -- Synthetic quartets from the cost pass ("a crossing is CHEAPER"), carried on the same rails
  -- as the forced pairs. Must run AFTER the pair loop: proven pairs are stored at `W.wires[W.n]`
  -- where W.n is not #W.wires, so injecting first gets silently overwritten. W.n is left alone
  -- (it counts PROVEN pairs and gates the site budget and min-crossing bound); only `quartet`
  -- and `wires` grow. Every appended entry must carry vn/hn: the diagnostic formats them with %d.
  if elro._crossQuartets then
    for _, q in ipairs(elro._crossQuartets) do
      local S = q[1]
      for i = 2, 4 do if q[i] < S then S = q[i] end end
      -- the two EDGES the turning window named, in the prover's own key form
      local e1, e2 = ekey(q[1], q[2]), ekey(q[3], q[4])
      -- A curl names one edge per side; a FACE publishes q.ves/q.hes as sets, and every
      -- combination must be legal -- the used site is decided by the ring's drawn shape.
      local ves, hes = {}, {}
      for _, k in ipairs(q.ves or { e1 }) do ves[k] = true end
      for _, k in ipairs(q.hes or { e2 }) do hes[k] = true end
      local vn, hn = 0, 0
      for _ in pairs(ves) do vn = vn + 1 end
      for _ in pairs(hes) do hn = hn + 1 end
      W.quartet[#W.quartet + 1] = { q[1], q[2], q[3], q[4], cost = true }
      W.wires[#W.wires + 1] = { S = S, vm = q.ring or {}, hm = {}, ves = ves, hes = hes,
                                vn = vn, hn = hn, cost = true }
      -- Registering the pair makes the walk ACCEPT the crossing (`W.pair` is the acceptance
      -- set). The keys also go on their own set `CK`: the lever-ranking exemption must apply to
      -- COST pairs only, never to the proven pairs that share `W.pair`.
      local CK = elro._crossPairKeys or {} ; elro._crossPairKeys = CK
      for k1 in pairs(ves) do
        for k2 in pairs(hes) do
          local ck = crosspair(k1, k2)
          W.pair[ck] = true ; W.pairIdx[ck] = #W.wires
          CK[ck] = true
        end
      end
    end
  end
  -- Publish what the build found, separately from what the walk went on to use.
  elro._wcPairs, elro._wcMin, elro._wcRan = W.n, W.min, true
  elro._wcCycles, elro._wcArcs = W.cycles, W.sameClassArcs
  if elro.debug or W.n > 0 or W.cycles > 0 or W.sameClassArcs > 0 then
    elro.tr(string.format("wire crossings: %d forced pair(s), min crossings >= %d"
      .. " | infeasible: %d cycle-class(es), %d same-class order arc(s)",
      W.n, W.min, W.cycles, W.sameClassArcs))
    for _, p in ipairs(W.wires) do
      -- A cost pair has no witness roles or site sets; it must print through its own format.
      if p.cost then
        elro.tr(string.format("  cost pair (crossCostTau): seed %s, ring of %d room(s)"
          .. " -- a crossing is CHEAPER here, not forced", tostring(p.S), #(p.vm or {})))
      else
        elro.tr(string.format("  wire pair: column of %d x row of %d -- witness %s/%s x %s/%s,"
          .. " %d v-site(s) x %d h-site(s)", #p.vm, #p.hm, tostring(p.S), tostring(p.N),
          tostring(p.W), tostring(p.E), p.vn, p.hn))
      end
    end
    for _, b in ipairs(W.badArcs) do
      elro.tr("  UNSATISFIABLE: strict order demanded inside one equality class: " .. b)
    end
  end
  return W
end
function elro.wire_site_min(p, coord)
  local best = nil
  for vk in pairs(p.ves) do
    local vu, vv = vk:match("^(%d+):(%d+)$")
    local a, b = coord[tonumber(vu)], coord[tonumber(vv)]
    if a and b then
      for hk in pairs(p.hes) do
        local k = crosspair(vk, hk)
        if best == nil or k < best then
          local hu, hv = hk:match("^(%d+):(%d+)$")
          local c, d = coord[tonumber(hu)], coord[tonumber(hv)]
          -- a shared endpoint means the wires meet AT A ROOM, which is not a crossing at all
          if c and d and vu ~= hu and vu ~= hv and vv ~= hu and vv ~= hv then
            local d1 = ori(c[1], c[2], d[1], d[2], a[1], a[2])
            local d2 = ori(c[1], c[2], d[1], d[2], b[1], b[2])
            if (d1 > 0) ~= (d2 > 0) then
              local d3 = ori(a[1], a[2], b[1], b[2], c[1], c[2])
              local d4 = ori(a[1], a[2], b[1], b[2], d[1], d[2])
              if (d3 > 0) ~= (d4 > 0) then best = k end
            end
          end
        end
      end
    end
  end
  return best
end
